Implement Metros and update the default OS and location
packethost/docker-machine-driver-packet pull request #62
Opened 2021-04-23 21:39 UTC by displague

Fixes #60 
Fixes #61

2021-04-23 22:10 UTC, jmarhee requested changes
Just that one note, but otherwise, ran as expected.

2021-04-23 22:10 UTC, jmarhee commented on pkg/drivers/metal/metal.go
> +	defaultMetro    = "DC"
The metro should be lower-cased:

```
$ docker-machine create sloth --driver metal --metal-api-key=$API_KEY --metal-project-id=$PROJECT --metal-plan "baremetal_0" --metal-metro-code "DC"
Running pre-create checks...
Error with pre-create check: "metal requires a valid metro"
```
Runs as expected with `"dc"` from the CLI

2021-04-26 12:02 UTC, displague commented on pkg/drivers/metal/metal.go
> +	defaultMetro    = "DC"
I intended to change the default plan from baremetal_0 to c3.small.x86 so that the defaults would accommodate more users (new users).

2021-04-26 17:56 UTC, jmarhee approved these changes
Looks great!

2021-05-20 02:49 UTC, merged